exports.STREAMS = 'http://etherx.jabber.org/streams'
exports.SESSION = 'urn:ietf:params:xml:ns:xmpp-session'
exports.BIND = 'urn:ietf:params:xml:ns:xmpp-bind'
exports.DELAY = 'urn:xmpp:delay'
exports.PRE_APPROVAL = 'urn:xmpp:features:pre-approval'
